import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={cn("h-full", "antialiased", "yekan")}>
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
